### ISSUE TITLE
Issue with alerting basic rules on Issue category

### ISSUE THREAD

**Issue by chaitanya-toddleapp** [grafana/sentry-datasource#266]
I'm experiencing an issue while alerting basic rules on the Issue category of our project. The issue occurs when I attempt to set up basic alerting rules. Following error message is displayed
`[sse.read Data Error] got error: input data must be a wide series but got type long (input refid)`

Steps to Reproduce:
- Create a new rule
- Select Sentry as the Data Source
- Select Issues as Query Type
- Select Project and Environment
- Press Shift + Enter to execute the query 

Expected Behavior:
The query should get successfully executed and get a date in the result

Actual Behavior:
The following error is encountered during the configuration process, preventing the setup of alerting rules:
`[sse.read Data Error] got error: input data must be a wide series but got type long (input refid)
`
Screenshots:
<img width="1440" alt="Screenshot 2024-06-04 at 11 21 43 AM" src="https://github.com/grafana/sentry-datasource/assets/116151198/32353a25-da1f-4085-b1bf-0874f84cb982">

Sentry Plugin Version - 1.8.0
Grafana - v10.2.0

**Comment by adamyeats** [comment]
@chaitanya-toddleapp It looks like you're encountering this error because an Issues query alone isn't enough to create an alert in Grafana. Grafana can't figure out how to use the data from this query to determine when to trigger an alert. It doesn't know which properties from the Sentry response should be used as metrics.

To solve this, you'll need to use an expression or aggregation (via the "Query" box) to transform the data into a format Grafana can work with. I think this could be better documented, so I'll work with my team to improve the documentation here.

In the meantime, could you let me know exactly what you're trying to achieve with your alert? For instance, if you want to be alerted when the number of events increases, a Stats query might be more appropriate.

**Comment by bossinc** [comment]
Closing. Feel free to reopen if this isn't resolved

**Comment by omri-shilton** [comment]
@chaitanya-toddleapp did you end up solving this issue?
we are also experiencing this issue
